version: '3'
services:
  grafana:
     container_name: grafana
     image: grafana/grafana:latest
     ports:
        - 3000:3000
        - 9100:9100
     volumes:
       - grafana:/var/lib/grafana
       - ./node_exporter.service:/etc/systemd/system/node_exporter.service
     environment:
        - GF_SECURITY_ADMIN_PASSWORD=grafana
        - GF_INSTALL_PLUGINS=grafana-clock-panel
     network_mode: "host"
    #  networks:
    #   grafana-loki:
    #     ipv4_address: 192.168.10.10