version: '3'
services:
  promtail:
      container_name: promtail-new
      image: grafana/promtail:latest
      volumes:
        - /var/log:/var/log
        - /var/lib/docker/containers/:/docker/logs/
        - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      command: -config.file=/etc/promtail/promtail-config.yaml
      ports:
        - 9080:9080
      network_mode: "host"
      # networks:
      #   grafana-loki:
      #     ipv4_address: 192.168.10.30